image: ruby:3.2

before_script:
  gem install asciidoctor-pdf asciidoctor-pdf-lists rouge

build_pdf:
  script:
    mkdir -p build
    asciidoctor-pdf -r asciidoctor-pdf -r asciidoctor-lists -r asciidoctor-diagram -r asciidoctor-mathematical doc/thesis.adoc -o build/thesis.pdf
  artifacts:
    paths:
      build/thesis.pdf

